"""initial_schema_v020

Revision ID: 50a73588923a
Revises: 
Create Date: 2026-09-22 14:56:26.215314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50a73588923a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('error_class', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingest_reports_document_id'), 'ingest_reports', ['document_id'], unique=False)
    op.create_index(op.f('ix_ingest_reports_file_hash'), 'ingest_reports', ['file_hash'], unique=False)
    op.create_index(op.f('ix_ingest_reports_id'), 'ingest_reports', ['id'], unique=False)
    op.create_index(op.f('ix_ingest_reports_status'), 'ingest_reports', ['status'], unique=False)
    op.create_index(op.f('ix_ingest_reports_workspace_id'), 'ingest_reports', ['workspace_id'], unique=False)
    op.add_column('document_chunks', sa.Column('locator', sa.String(length=255), nullable=True))
    op.add_column('document_chunks', sa.Column('citation', sa.String(length=512), nullable=True))
    op.alter_column('document_chunks', 'page_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('document_chunks', 'embedding',
               existing_type=sa.NUMERIC(precision=1024),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               existing_nullable=True)
    op.create_index('ix_chunks_doc_page', 'document_chunks', ['document_id', 'page_number'], unique=False)
    op.add_column('documents', sa.Column('mime', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('parser_version', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('original_path', sa.String(length=1024), nullable=True))
    op.add_column('documents', sa.Column('mtime', sa.Float(), nullable=True))
    op.add_column('documents', sa.Column('extra', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'extra')
    op.drop_column('documents', 'mtime')
    op.drop_column('documents', 'original_path')
    op.drop_column('documents', 'parser_version')
    op.drop_column('documents', 'mime')
    op.drop_index('ix_chunks_doc_page', table_name='document_chunks')
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               type_=sa.NUMERIC(precision=1024),
               existing_nullable=True)
    op.alter_column('document_chunks', 'page_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('document_chunks', 'citation')
    op.drop_column('document_chunks', 'locator')
    op.drop_index(op.f('ix_ingest_reports_workspace_id'), table_name='ingest_reports')
    op.drop_index(op.f('ix_ingest_reports_status'), table_name='ingest_reports')
    op.drop_index(op.f('ix_ingest_reports_id'), table_name='ingest_reports')
    op.drop_index(op.f('ix_ingest_reports_file_hash'), table_name='ingest_reports')
    op.drop_index(op.f('ix_ingest_reports_document_id'), table_name='ingest_reports')
    op.drop_table('ingest_reports')
    # ### end Alembic commands ###
